@host=https://localhost:7105

POST {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImN0eSI6IkpXVCJ9.eyJzdWIiOiJkZjBkODY1OS04ZjljLTRkZDAtODMyYS05ZWZlMDQzY2FhMWUiLCJnaXZlbl9uYW1lIjoiw5ZtZXIgRmFydWsiLCJmYW1pbHlfbmFtZSI6IsOHZWxpayIsImp0aSI6IjhiMTRkY2IyLWY5YmEtNDBlOS1hZGM3LTAwN2Q1ODJlZGZjYiIsImV4cCI6MTY2MTM3NTg0MSwiaXNzIjoiRGlubmVySG9zdGluZyIsImF1ZCI6IkRpbm5lckhvc3RpbmcifQ.LLervpILdcgW67GXjXsxY50ycg7UnhL7ALQN518Jz5g